---
title: 'OctaPi: brute-force Enigma'
hero_image: images/banner.png
description: Find out how to launch a brute-force crypt attack on Enigma
theme: red
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-11-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: What is Enigma, and how does it work?
- title: Enigma in use during WWII
- title: Encrypt a message
- title: Decrypt a message
- title: Standalone crypt attack
- title: Crypt attack using OctaPi
  completion: internal
- title: 'Challenge: find out more'
